# Generated by Django 3.1.2 on 2023-07-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='prueba',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='prueba',
        ),
    ]
